---
# handlers file for vhub-cluster
- name: Restart NetworkManager
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: NetworkManager

- name: Restart dnsmasq
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: dnsmasq.service
