all:
  children:
    slcm_nokia_cloud_ran_bastion:
      hosts:
        bastion-vhub-node:
          ansible_host: "{{ lookup('ansible.builtin.env', 'BASTION_VHUB_HOST') }}"
          libvirt:
            pool:
              name: "{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}"
              path: "{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_POOL_PATH') }}"
          kcli:
            clusters:
            - type: openshift
              force_installation: true
              parameters:
                cluster: "{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}"
                version: "{{ lookup('ansible.builtin.env', 'CLUSTER_VERSION') }}"
                tag: "{{ lookup('ansible.builtin.env', 'CLUSTER_TAG') }}"
                domain: "{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}"
                pool: "{{libvirt.pool.name}}"
                nets:
                  - baremetal
                  - provisioning
                keys:
                  - "{{ lookup('ansible.builtin.env', 'CLUSTER_SSH_PUB_KEY') }}"
                ctlplanes: 3
                workers: 0
                memory: 32000
                numcpus: 16
                disks:
                  - 200
                  - 200
                base64_pull_secret: "{{ lookup('ansible.builtin.env', 'CLUSTER_B64_PULL_SECRET') }}"
                api_ip: "{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_API_IP') }}"
                ingress_ip: "{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_INGRESS_IP') }}"
                apps:
                  - local-storage-operator
                  - openshift-gitops-operator
                  - advanced-cluster-management
                  - topology-aware-lifecycle-manager
                  - multicluster-engine
                vmrules:
                - vhub-ocp-ctlplane-0:
                    nets:
                      - name: baremetal
                        mac: "{{ lookup('ansible.builtin.env', 'CLUSTER_BRIDGE_NIC_MAC_0') }}"
                - vhub-ocp-ctlplane-1:
                    nets:
                      - name: baremetal
                        mac: "{{ lookup('ansible.builtin.env', 'CLUSTER_BRIDGE_NIC_MAC_1') }}"
                - vhub-ocp-ctlplane-2:
                    nets:
                      - name: baremetal
                        mac: "{{ lookup('ansible.builtin.env', 'CLUSTER_BRIDGE_NIC_MAC_2') }}"
          credentials:
            clusters_details: ~/.kcli/clusters
            kubeconfig: auth/kubeconfig
            kubeadmin_password: auth/kubeadmin-password
          dnsmasq:
            drop_in_files:
              - path: /etc/dnsmasq.d/70-{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}.conf
                content: |
                  # /etc/dnsmasq.d/70-{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}.conf
                  # This file sets up the local OCP cluster domain and defines some aliases and a wildcard.
                  local=/{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}/
                  # OCP cluster API
                  address=/api.{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}/{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_API_IP') }}
                  address=/api-int.{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}/{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_API_IP') }}
                  # OCP cluster INGRESS
                  address=/.apps.{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}.{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_DOMAIN') }}/{{ lookup('ansible.builtin.env', 'CLUSTER_NOKIA_CLOUD_RAN_INGRESS_IP') }}
