---
- name: Rollback openshift cluster
  when: "'rollback' in ansible_run_tags"
  tags:
    - rollback
  block:

    - name: Deleting '{{kcli.parameters.cluster}}' cluster
      ansible.builtin.shell: |-
        kcli delete cluster {{kcli.parameters.cluster}} --yes
      register: del_cluster_ret
      changed_when: del_cluster_ret.stdout != ''

    # - name: Clean up generated dnsmasq drop-in files
    #   ansible.builtin.include_tasks: ./dnsmasq.yml

- name: Deploy openshift cluster
  block:

    - name: Create temporary kcli cluster parameter file
      ansible.builtin.tempfile:
        state: directory
        prefix: kcli_
      register: kcli_tempdir

    - name: Dump base64 pull_secret to a local temporary file
      when: kcli.parameters.base64_pull_secret is defined
      ansible.builtin.shell: |-
        echo "{{kcli.parameters.base64_pull_secret}}" | base64 -d > {{kcli_tempdir.path}}/pull_secret.yml

    - name: Update pull_secret path to the dumped local temporary file
      when: kcli.parameters.base64_pull_secret is defined
      ansible.builtin.set_fact:
        kcli: "{{updated_kcli}}"
      vars:
        updated_kcli: |-
          {% set _ = kcli.parameters.update({'base64_pull_secret': None, 'pull_secret': (kcli_tempdir.path + "/pull_secret.yml")}) %}
          {{kcli}}

    - name: Update KCLI 'pull_secret' paramater
      when: kcli.parameters.base64_pull_secret is defined
      ansible.builtin.command: |-
        echo "{{kcli.parameters.base64_pull_secret}}" > {{kcli_tempdir.path}}/pull_secret.yml

    - name: Create a k8s cluster
      ansible.builtin.shell: |-
        cat << EOF > {{kcli_tempdir.path}}/cluster_parameters.yml
        {{kcli.parameters | to_nice_yaml}}
        EOF
        kcli create cluster openshift \
          --paramfile={{kcli_tempdir.path}}/cluster_parameters.yml
      async: 14400
      poll: 0
      register: kcli_cluster
      changed_when: false

    # - name: Generate dnsmasq drop-in files
    #   ansible.builtin.include_tasks: ./dnsmasq.yml

    - name: Check cluster installation progess
      async_status:
        jid: "{{kcli_cluster.ansible_job_id}}"
      register: kcli_job_result
      until: kcli_job_result.finished
      retries: 120
      delay: 120
      # changed_when: kcli_job_result.rc is defined and kcli_job_result.rc == 0
      # failed_when: |-
      #   kcli_job_result.stderr != '' and kcli_job_result.rc != 0

    # - name: Force all notified handlers to run at this point, not waiting for normal sync points
    #   ansible.builtin.meta: flush_handlers

    - name: Show installed cluster
      changed_when: false
      ansible.builtin.shell: |-
        kcli list cluster
        kcli list plan
        kcli list vms
        which oc 2> /dev/null && \
          oc --kubeconfig ~/.kcli/clusters/{{kcli.parameters.cluster}}/auth/kubeconfig get node -owide

  always:

    - name: Remove temporaty kcli cluster parameter file
      ansible.builtin.file:
        path: "{{item}}"
        state: absent
      loop:
        - "{{kcli_tempdir.path}}"
