---
- name: Deploy openshift cluster
  block:

    - name: Create temporary kcli plan file
      ansible.builtin.tempfile:
        state: file
        prefix: kcli_plan_
        suffix: .yml
      register: kcli_plan_yaml

    - name: Create a k8s cluster
      ansible.builtin.shell: |-
        cat << EOF > {{kcli_plan_yaml.path}}
        {{kcli.parameters | to_nice_yaml}}
        EOF
        kcli create cluster openshift --paramfile={{kcli_plan_yaml.path}}
      async: 7200
      poll: 0
      register: kcli_plan

    - name: Show cluster installation progess
      async_status:
        jid: "{{kcli_plan.ansible_job_id}}"
      register: kcli_job_result
      until: kcli_job_result.finished
      retries: 120
      delay: 60

    - name: Show installed cluster
      ansible.builtin.shell: |-
        kcli list plan
        kcli list cluster
        kcli list vms
        oc --kubeconfig ~/.kcli/clusters/{{kcli.parameters.cluster}}/auth/kubeconfig get node -owide

  always:

    - name: Remove temporaty kcli plan file
      ansible.builtin.file:
        path: "{{item}}"
        state: absent
      loop:
        - "{{kcli_plan_yaml.path}}"
