---
- name: Get credential file both in plain text and base64
  ansible.builtin.command: |-
    cat {{ k8s.kubeconfig }}
  register: kc_config

- name: Get credential file both in plain text and base64
  ansible.builtin.command: |-
    cat {{ k8s.kubeadmin_password }}
  register: kubeadmin_password_pass

- name: Get cluster credential
  ansible.builtin.set_fact:
    kubeconfig: "{{ kc | from_yaml }}"
    b64_kubeconfig: "{{ kc | b64encode }}"
    kubeadmin_password: "{{ kubeadmin_password_pass.stdout }}"
  vars:
    kc: |-
      {{ kc_config.stdout }}
