---
- name: Cluster credentials
  when: credentials.clusters_details is defined and
        credentials.kubeconfig is defined and
        credentials.kubeadmin_password is defined
  block:

    - name: Get pass and credential file (both in plain text and base64)
      ansible.builtin.shell: |-
        B64_KC=$(cat {{credentials.clusters_details}}/{{cluster.parameters.cluster}}/{{credentials.kubeconfig}} | base64 -w 0)
        KADM_PASS=$(cat {{credentials.clusters_details}}/{{cluster.parameters.cluster}}/{{credentials.kubeadmin_password}})
        echo "{{cluster.parameters.cluster}}"
        echo "${B64_KC}"
        echo "${KADM_PASS}"
      register: clusters_creds
      loop: "{{kcli.clusters}}"
      loop_control:
        loop_var: cluster

    - name: Get cluster credential
      ansible.builtin.set_fact:
        credentials: |-
          {% set credentials_by_cluster_name = {} %}
          {% for k in clusters_creds.results %}
          {%   set cluster_name = k.stdout_lines.0 %}
          {%   set b64_kc =  k.stdout_lines.1 %}
          {%   set kc = (b64_kc | b64decode | from_yaml) %}
          {%   set kadm_pass = k.stdout_lines.2 %}
          {%   set cluster_cred = { cluster_name: {"kubeconfig": kc, "b64_kubeconfig": b64_kc, "kubeadmin_password": kadm_pass}} %}
          {%   set _ = credentials_by_cluster_name.update(cluster_cred) %}
          {% endfor %}
          {{ credentials_by_cluster_name }}
